version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - config/.env
    depends_on:
      - llm-agent

  llm-agent:
    build:
      context: ./agents/llm-agent
      dockerfile: Dockerfile
    ports:
      - "5080:5080"
    # Inherit the OPENAI_API_KEY from your host environment.
    # You can also specify this in a .env file or override it as needed.
    env_file:
      - config/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  neo4j:
    image: neo4j:4.4
    ports:
      - "7687:7687"
      - "7474:7474"
    env_file:
      - config/.env
    volumes:
      - neo4j_data:/data
  
  neo4j-agent:
    build:
      context: ./knowledge-base/knowledge-graph-agent
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - neo4j
    env_file:
      - config/.env

volumes:
  neo4j_data:
